<gconfentryfile>
  <entrylist base="/system/networking/connections">
    <entry>
      <key>%NUMBER%/802-11-wireless/name</key>
      <value>
        <string>802-11-wireless</string>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/802-11-wireless/security</key>
      <value>
        <string>802-11-wireless-security</string>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/802-11-wireless/ssid</key>
      <value>
        <list type="int">
            <value>
              <int>105</int>
            </value>
            <value>
              <int>110</int>
            </value>
            <value>
              <int>116</int>
            </value>
            <value>
              <int>101</int>
            </value>
            <value>
              <int>114</int>
            </value>
            <value>
              <int>110</int>
            </value>
            <value>
              <int>101</int>
            </value>
            <value>
              <int>116</int>
            </value>
        </list>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/802-11-wireless-security/key-mgmt</key>
      <value>
        <string>wpa-eap</string>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/802-11-wireless-security/name</key>
      <value>
        <string>802-11-wireless-security</string>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/802-1x/eap</key>
      <value>
        <list type="string">
            <value>
              <string>tls</string>
            </value>
        </list>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/802-1x/identity</key>
      <value>
        <string>$matricola</string>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/802-1x/name</key>
      <value>
        <string>802-1x</string>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/802-1x/nma-path-ca-cert</key>
      <value>
        <string>/etc/asi.cer</string>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/802-1x/nma-path-client-cert</key>
      <value>
        <string>/etc/CertificatoASI.p12</string>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/802-1x/nma-path-private-key</key>
      <value>
        <string>/etc/CertificatoASI.p12</string>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/connection/autoconnect</key>
      <value>
        <bool>true</bool>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/connection/id</key>
      <value>
        <string>internet</string>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/connection/name</key>
      <value>
        <string>connection</string>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/connection/type</key>
      <value>
        <string>802-11-wireless</string>
      </value>
    </entry>
    <entry>
      <key>%NUMBER%/connection/uuid</key>
      <value>
        <string>444d984f-672a-46f7-8085-c9c9259be40f</string>
      </value>
    </entry>
  </entrylist>
</gconfentryfile>
