# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard.ui'
#
# Created: Tue Feb 22 17:03:58 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_poliwifi(object):
    def setupUi(self, poliwifi):
        poliwifi.setObjectName(_fromUtf8("poliwifi"))
        poliwifi.resize(523, 459)
        poliwifi.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.p1_welcome = QtGui.QWizardPage()
        self.p1_welcome.setObjectName(_fromUtf8("p1_welcome"))
        self.verticalLayout = QtGui.QVBoxLayout(self.p1_welcome)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.p1_welcome)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setWordWrap(True)
        self.label.setMargin(10)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.polimi_status = QtGui.QLabel(self.p1_welcome)
        self.polimi_status.setEnabled(True)
        self.polimi_status.setObjectName(_fromUtf8("polimi_status"))
        self.verticalLayout.addWidget(self.polimi_status)
        self.polimi_statusbar = QtGui.QProgressBar(self.p1_welcome)
        self.polimi_statusbar.setMaximum(0)
        self.polimi_statusbar.setProperty(_fromUtf8("value"), 25612)
        self.polimi_statusbar.setTextVisible(True)
        self.polimi_statusbar.setObjectName(_fromUtf8("polimi_statusbar"))
        self.verticalLayout.addWidget(self.polimi_statusbar)
        poliwifi.addPage(self.p1_welcome)
        self.p2_login = QtGui.QWizardPage()
        self.p2_login.setObjectName(_fromUtf8("p2_login"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.p2_login)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_3 = QtGui.QLabel(self.p2_login)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_4 = QtGui.QLabel(self.p2_login)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.p2_login)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.personCode = QtGui.QLineEdit(self.p2_login)
        self.personCode.setMaxLength(10)
        self.personCode.setEchoMode(QtGui.QLineEdit.Normal)
        self.personCode.setPlaceholderText(_fromUtf8(""))
        self.personCode.setObjectName(_fromUtf8("personCode"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.personCode)
        self.personCodePwd = QtGui.QLineEdit(self.p2_login)
        self.personCodePwd.setInputMask(_fromUtf8(""))
        self.personCodePwd.setMaxLength(32767)
        self.personCodePwd.setEchoMode(QtGui.QLineEdit.Password)
        self.personCodePwd.setObjectName(_fromUtf8("personCodePwd"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.personCodePwd)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        poliwifi.addPage(self.p2_login)
        self.p3_config = QtGui.QWizardPage()
        self.p3_config.setObjectName(_fromUtf8("p3_config"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.p3_config)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.label_10 = QtGui.QLabel(self.p3_config)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_4.addWidget(self.label_10)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_7 = QtGui.QLabel(self.p3_config)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.p3_config)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.p3_config)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.matricola = QtGui.QLineEdit(self.p3_config)
        self.matricola.setObjectName(_fromUtf8("matricola"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.matricola)
        self.certificatepassword = QtGui.QLineEdit(self.p3_config)
        self.certificatepassword.setObjectName(_fromUtf8("certificatepassword"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.certificatepassword)
        self.usertype = QtGui.QComboBox(self.p3_config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usertype.sizePolicy().hasHeightForWidth())
        self.usertype.setSizePolicy(sizePolicy)
        self.usertype.setObjectName(_fromUtf8("usertype"))
        self.usertype.addItem(_fromUtf8(""))
        self.usertype.addItem(_fromUtf8(""))
        self.usertype.addItem(_fromUtf8(""))
        self.usertype.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.usertype)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        poliwifi.addPage(self.p3_config)
        self.p4_download = QtGui.QWizardPage()
        self.p4_download.setObjectName(_fromUtf8("p4_download"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.p4_download)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.progress_status = QtGui.QLabel(self.p4_download)
        self.progress_status.setText(_fromUtf8(""))
        self.progress_status.setObjectName(_fromUtf8("progress_status"))
        self.verticalLayout_3.addWidget(self.progress_status)
        self.progress_statusbar = QtGui.QProgressBar(self.p4_download)
        self.progress_statusbar.setProperty(_fromUtf8("value"), 24)
        self.progress_statusbar.setObjectName(_fromUtf8("progress_statusbar"))
        self.verticalLayout_3.addWidget(self.progress_statusbar)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.deownload_complete = QtGui.QLabel(self.p4_download)
        self.deownload_complete.setObjectName(_fromUtf8("deownload_complete"))
        self.verticalLayout_3.addWidget(self.deownload_complete)
        poliwifi.addPage(self.p4_download)
        self.p5_connect = QtGui.QWizardPage()
        self.p5_connect.setObjectName(_fromUtf8("p5_connect"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.p5_connect)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        self.label_11 = QtGui.QLabel(self.p5_connect)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_5.addWidget(self.label_11)
        self.connectnow = QtGui.QCheckBox(self.p5_connect)
        self.connectnow.setChecked(True)
        self.connectnow.setObjectName(_fromUtf8("connectnow"))
        self.verticalLayout_5.addWidget(self.connectnow)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem13)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem14)
        poliwifi.addPage(self.p5_connect)

        self.retranslateUi(poliwifi)
        QtCore.QMetaObject.connectSlotsByName(poliwifi)

    def retranslateUi(self, poliwifi):
        poliwifi.setWindowTitle(QtGui.QApplication.translate("poliwifi", "PoliWifi", None, QtGui.QApplication.UnicodeUTF8))
        self.p1_welcome.setTitle(QtGui.QApplication.translate("poliwifi", "Welcome", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("poliwifi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">This wizard will help your configure yuor computer for using Politecnico di Milano\'s wireless network.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">This program has developed by POuL ( </span><a href=\"http://www.poul.org/\"><span style=\" text-decoration: underline; color:#0057ae;\">http://www.poul.org/</span></a><span style=\" font-size:10pt;\"> )</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.polimi_status.setText(QtGui.QApplication.translate("poliwifi", "Connecting to polimi...", None, QtGui.QApplication.UnicodeUTF8))
        self.polimi_statusbar.setFormat(QtGui.QApplication.translate("poliwifi", "Connecting to \"polimi\"...", None, QtGui.QApplication.UnicodeUTF8))
        self.p2_login.setTitle(QtGui.QApplication.translate("poliwifi", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("poliwifi", "Please insert your credentials for access to Politecnico di Milano", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("poliwifi", "Personal Code:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("poliwifi", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.p3_config.setTitle(QtGui.QApplication.translate("poliwifi", "Connection configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("poliwifi", "Please insert configuration details.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("poliwifi", "Id. Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("poliwifi", "User Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("poliwifi", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.certificatepassword.setPlaceholderText(QtGui.QApplication.translate("poliwifi", "Insert new password for certificate", None, QtGui.QApplication.UnicodeUTF8))
        self.usertype.setItemText(0, QtGui.QApplication.translate("poliwifi", "Student", None, QtGui.QApplication.UnicodeUTF8))
        self.usertype.setItemText(1, QtGui.QApplication.translate("poliwifi", "Professor", None, QtGui.QApplication.UnicodeUTF8))
        self.usertype.setItemText(2, QtGui.QApplication.translate("poliwifi", "Techical Staff", None, QtGui.QApplication.UnicodeUTF8))
        self.usertype.setItemText(3, QtGui.QApplication.translate("poliwifi", "Guest", None, QtGui.QApplication.UnicodeUTF8))
        self.p4_download.setTitle(QtGui.QApplication.translate("poliwifi", "Download Certificate", None, QtGui.QApplication.UnicodeUTF8))
        self.deownload_complete.setText(QtGui.QApplication.translate("poliwifi", "Download is complete. Please proceed to the next page.", None, QtGui.QApplication.UnicodeUTF8))
        self.p5_connect.setTitle(QtGui.QApplication.translate("poliwifi", "Finish", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("poliwifi", "You have successfully configured your computer for connecting to internet.", None, QtGui.QApplication.UnicodeUTF8))
        self.connectnow.setText(QtGui.QApplication.translate("poliwifi", "Connect Now", None, QtGui.QApplication.UnicodeUTF8))

